// ===== PROJECTS =====
export const LOAD_PROJECTS_SUCCESS = 'LOAD_PROJECTS_SUCCESS';  
export const ADD_PROJECT_SUCCESS = 'ADD_PROJECT_SUCCESS';  
export const DELETE_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS';  

// ===== TASKS =====
export const ADD_TASK_SUCCESS = 'ADD_TASK_SUCCESS';  
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS';  
