// ===== PROJECTS =====
export const LOAD_PROJECTS_SUCCESS = 'LOAD_PROJECTS_SUCCESS';  
export const ADD_PROJECT_SUCCESS = 'ADD_PROJECT_SUCCESS';  
export const DELETE_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS';  
